// Vendored from canonical source calystral-io/core/core-api/proto (do not edit by hand; sync via `make proto-sync`).

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.29.3
// source: mutate.proto

// Write-path surface: transactional mutations against the embedded engine.
// Concrete handlers land in a later lane; this lane defines the wire shape and
// a stubbed service that returns UNIMPLEMENTED.

package mutatepb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MutationKind int32

const (
	// Unset; rejected by the handler.
	MutationKind_MUTATION_KIND_UNSPECIFIED MutationKind = 0
	// Create a node anchor.
	MutationKind_MUTATION_KIND_CREATE_NODE MutationKind = 1
	// Create an edge between two anchors.
	MutationKind_MUTATION_KIND_CREATE_EDGE MutationKind = 2
	// Update an existing anchor in place.
	MutationKind_MUTATION_KIND_UPDATE MutationKind = 3
	// Close (logically delete) an anchor.
	MutationKind_MUTATION_KIND_CLOSE MutationKind = 4
)

// Enum value maps for MutationKind.
var (
	MutationKind_name = map[int32]string{
		0: "MUTATION_KIND_UNSPECIFIED",
		1: "MUTATION_KIND_CREATE_NODE",
		2: "MUTATION_KIND_CREATE_EDGE",
		3: "MUTATION_KIND_UPDATE",
		4: "MUTATION_KIND_CLOSE",
	}
	MutationKind_value = map[string]int32{
		"MUTATION_KIND_UNSPECIFIED": 0,
		"MUTATION_KIND_CREATE_NODE": 1,
		"MUTATION_KIND_CREATE_EDGE": 2,
		"MUTATION_KIND_UPDATE":      3,
		"MUTATION_KIND_CLOSE":       4,
	}
)

func (x MutationKind) Enum() *MutationKind {
	p := new(MutationKind)
	*p = x
	return p
}

func (x MutationKind) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MutationKind) Descriptor() protoreflect.EnumDescriptor {
	return file_mutate_proto_enumTypes[0].Descriptor()
}

func (MutationKind) Type() protoreflect.EnumType {
	return &file_mutate_proto_enumTypes[0]
}

func (x MutationKind) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MutationKind.Descriptor instead.
func (MutationKind) EnumDescriptor() ([]byte, []int) {
	return file_mutate_proto_rawDescGZIP(), []int{0}
}

type MutateRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Tenant the mutation is scoped to. Set by the gateway-verified principal.
	Tenant string `protobuf:"bytes,1,opt,name=tenant,proto3" json:"tenant,omitempty"`
	// The mutations to apply, in order, within a single transaction.
	Mutations     []*Mutation `protobuf:"bytes,2,rep,name=mutations,proto3" json:"mutations,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MutateRequest) Reset() {
	*x = MutateRequest{}
	mi := &file_mutate_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MutateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MutateRequest) ProtoMessage() {}

func (x *MutateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mutate_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MutateRequest.ProtoReflect.Descriptor instead.
func (*MutateRequest) Descriptor() ([]byte, []int) {
	return file_mutate_proto_rawDescGZIP(), []int{0}
}

func (x *MutateRequest) GetTenant() string {
	if x != nil {
		return x.Tenant
	}
	return ""
}

func (x *MutateRequest) GetMutations() []*Mutation {
	if x != nil {
		return x.Mutations
	}
	return nil
}

type Mutation struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The mutation kind.
	Kind MutationKind `protobuf:"varint,1,opt,name=kind,proto3,enum=calystral.core.v1.mutate.MutationKind" json:"kind,omitempty"`
	// Engine-encoded operation payload (cybr value bytes).
	Payload       []byte `protobuf:"bytes,2,opt,name=payload,proto3" json:"payload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Mutation) Reset() {
	*x = Mutation{}
	mi := &file_mutate_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Mutation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Mutation) ProtoMessage() {}

func (x *Mutation) ProtoReflect() protoreflect.Message {
	mi := &file_mutate_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Mutation.ProtoReflect.Descriptor instead.
func (*Mutation) Descriptor() ([]byte, []int) {
	return file_mutate_proto_rawDescGZIP(), []int{1}
}

func (x *Mutation) GetKind() MutationKind {
	if x != nil {
		return x.Kind
	}
	return MutationKind_MUTATION_KIND_UNSPECIFIED
}

func (x *Mutation) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

type MutateResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The committed transaction id.
	TxnId uint64 `protobuf:"varint,1,opt,name=txn_id,json=txnId,proto3" json:"txn_id,omitempty"`
	// Number of anchors affected by the transaction.
	Affected      uint64 `protobuf:"varint,2,opt,name=affected,proto3" json:"affected,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MutateResponse) Reset() {
	*x = MutateResponse{}
	mi := &file_mutate_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MutateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MutateResponse) ProtoMessage() {}

func (x *MutateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_mutate_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MutateResponse.ProtoReflect.Descriptor instead.
func (*MutateResponse) Descriptor() ([]byte, []int) {
	return file_mutate_proto_rawDescGZIP(), []int{2}
}

func (x *MutateResponse) GetTxnId() uint64 {
	if x != nil {
		return x.TxnId
	}
	return 0
}

func (x *MutateResponse) GetAffected() uint64 {
	if x != nil {
		return x.Affected
	}
	return 0
}

var File_mutate_proto protoreflect.FileDescriptor

const file_mutate_proto_rawDesc = "" +
	"\n" +
	"\fmutate.proto\x12\x18calystral.core.v1.mutate\"i\n" +
	"\rMutateRequest\x12\x16\n" +
	"\x06tenant\x18\x01 \x01(\tR\x06tenant\x12@\n" +
	"\tmutations\x18\x02 \x03(\v2\".calystral.core.v1.mutate.MutationR\tmutations\"`\n" +
	"\bMutation\x12:\n" +
	"\x04kind\x18\x01 \x01(\x0e2&.calystral.core.v1.mutate.MutationKindR\x04kind\x12\x18\n" +
	"\apayload\x18\x02 \x01(\fR\apayload\"C\n" +
	"\x0eMutateResponse\x12\x15\n" +
	"\x06txn_id\x18\x01 \x01(\x04R\x05txnId\x12\x1a\n" +
	"\baffected\x18\x02 \x01(\x04R\baffected*\x9e\x01\n" +
	"\fMutationKind\x12\x1d\n" +
	"\x19MUTATION_KIND_UNSPECIFIED\x10\x00\x12\x1d\n" +
	"\x19MUTATION_KIND_CREATE_NODE\x10\x01\x12\x1d\n" +
	"\x19MUTATION_KIND_CREATE_EDGE\x10\x02\x12\x18\n" +
	"\x14MUTATION_KIND_UPDATE\x10\x03\x12\x17\n" +
	"\x13MUTATION_KIND_CLOSE\x10\x042l\n" +
	"\rMutateService\x12[\n" +
	"\x06Mutate\x12'.calystral.core.v1.mutate.MutateRequest\x1a(.calystral.core.v1.mutate.MutateResponseBBZ@github.com/calystral-io/studio/internal/corepb/mutatepb;mutatepbb\x06proto3"

var (
	file_mutate_proto_rawDescOnce sync.Once
	file_mutate_proto_rawDescData []byte
)

func file_mutate_proto_rawDescGZIP() []byte {
	file_mutate_proto_rawDescOnce.Do(func() {
		file_mutate_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_mutate_proto_rawDesc), len(file_mutate_proto_rawDesc)))
	})
	return file_mutate_proto_rawDescData
}

var file_mutate_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_mutate_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_mutate_proto_goTypes = []any{
	(MutationKind)(0),      // 0: calystral.core.v1.mutate.MutationKind
	(*MutateRequest)(nil),  // 1: calystral.core.v1.mutate.MutateRequest
	(*Mutation)(nil),       // 2: calystral.core.v1.mutate.Mutation
	(*MutateResponse)(nil), // 3: calystral.core.v1.mutate.MutateResponse
}
var file_mutate_proto_depIdxs = []int32{
	2, // 0: calystral.core.v1.mutate.MutateRequest.mutations:type_name -> calystral.core.v1.mutate.Mutation
	0, // 1: calystral.core.v1.mutate.Mutation.kind:type_name -> calystral.core.v1.mutate.MutationKind
	1, // 2: calystral.core.v1.mutate.MutateService.Mutate:input_type -> calystral.core.v1.mutate.MutateRequest
	3, // 3: calystral.core.v1.mutate.MutateService.Mutate:output_type -> calystral.core.v1.mutate.MutateResponse
	3, // [3:4] is the sub-list for method output_type
	2, // [2:3] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_mutate_proto_init() }
func file_mutate_proto_init() {
	if File_mutate_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_mutate_proto_rawDesc), len(file_mutate_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_mutate_proto_goTypes,
		DependencyIndexes: file_mutate_proto_depIdxs,
		EnumInfos:         file_mutate_proto_enumTypes,
		MessageInfos:      file_mutate_proto_msgTypes,
	}.Build()
	File_mutate_proto = out.File
	file_mutate_proto_goTypes = nil
	file_mutate_proto_depIdxs = nil
}
