// Vendored from canonical source calystral-io/core/core-api/proto (do not edit by hand; sync via `make proto-sync`).

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v5.29.3
// source: mutate.proto

// Write-path surface: transactional mutations against the embedded engine.
// Concrete handlers land in a later lane; this lane defines the wire shape and
// a stubbed service that returns UNIMPLEMENTED.

package mutatepb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	MutateService_Mutate_FullMethodName = "/calystral.core.v1.mutate.MutateService/Mutate"
)

// MutateServiceClient is the client API for MutateService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Applies mutations (node/edge create, update, close) within one transaction.
type MutateServiceClient interface {
	// Apply a batch of mutations atomically and return the commit outcome.
	Mutate(ctx context.Context, in *MutateRequest, opts ...grpc.CallOption) (*MutateResponse, error)
}

type mutateServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewMutateServiceClient(cc grpc.ClientConnInterface) MutateServiceClient {
	return &mutateServiceClient{cc}
}

func (c *mutateServiceClient) Mutate(ctx context.Context, in *MutateRequest, opts ...grpc.CallOption) (*MutateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MutateResponse)
	err := c.cc.Invoke(ctx, MutateService_Mutate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MutateServiceServer is the server API for MutateService service.
// All implementations must embed UnimplementedMutateServiceServer
// for forward compatibility.
//
// Applies mutations (node/edge create, update, close) within one transaction.
type MutateServiceServer interface {
	// Apply a batch of mutations atomically and return the commit outcome.
	Mutate(context.Context, *MutateRequest) (*MutateResponse, error)
	mustEmbedUnimplementedMutateServiceServer()
}

// UnimplementedMutateServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedMutateServiceServer struct{}

func (UnimplementedMutateServiceServer) Mutate(context.Context, *MutateRequest) (*MutateResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Mutate not implemented")
}
func (UnimplementedMutateServiceServer) mustEmbedUnimplementedMutateServiceServer() {}
func (UnimplementedMutateServiceServer) testEmbeddedByValue()                       {}

// UnsafeMutateServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MutateServiceServer will
// result in compilation errors.
type UnsafeMutateServiceServer interface {
	mustEmbedUnimplementedMutateServiceServer()
}

func RegisterMutateServiceServer(s grpc.ServiceRegistrar, srv MutateServiceServer) {
	// If the following call panics, it indicates UnimplementedMutateServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&MutateService_ServiceDesc, srv)
}

func _MutateService_Mutate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MutateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MutateServiceServer).Mutate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MutateService_Mutate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MutateServiceServer).Mutate(ctx, req.(*MutateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// MutateService_ServiceDesc is the grpc.ServiceDesc for MutateService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MutateService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "calystral.core.v1.mutate.MutateService",
	HandlerType: (*MutateServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Mutate",
			Handler:    _MutateService_Mutate_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "mutate.proto",
}
