// Vendored from canonical source calystral-io/core/core-api/proto (do not edit by hand; sync via `make proto-sync`).

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.29.3
// source: query.proto

// Read-path surface: CyQL query execution against the embedded engine. Compiles
// the CyQL to cybr, binds the request parameters, runs the query over the store,
// and returns the result rows.

package querypb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type QueryRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The CyQL query text.
	Cyql string `protobuf:"bytes,1,opt,name=cyql,proto3" json:"cyql,omitempty"`
	// Tenant the query is scoped to. Set by the gateway-verified principal.
	Tenant string `protobuf:"bytes,2,opt,name=tenant,proto3" json:"tenant,omitempty"`
	// Optional point-in-time read; unix milliseconds. 0 means "latest". Non-zero
	// (historical) reads are not honored yet and are rejected INVALID_ARGUMENT.
	AsOfUnixMs uint64 `protobuf:"varint,3,opt,name=as_of_unix_ms,json=asOfUnixMs,proto3" json:"as_of_unix_ms,omitempty"`
	// The query's bound parameter values, POSITIONAL: the compiler lowers each
	// read predicate's compared value to a LOAD_PARAM slot, in first-appearance
	// order, and these are bound into those slots in the same order. Each entry is
	// one cybr value encoded with the shared value codec (the same encoding
	// proc-invoke arguments use). A query with no predicate parameters sends none.
	Params        [][]byte `protobuf:"bytes,4,rep,name=params,proto3" json:"params,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryRequest) Reset() {
	*x = QueryRequest{}
	mi := &file_query_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryRequest) ProtoMessage() {}

func (x *QueryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_query_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryRequest.ProtoReflect.Descriptor instead.
func (*QueryRequest) Descriptor() ([]byte, []int) {
	return file_query_proto_rawDescGZIP(), []int{0}
}

func (x *QueryRequest) GetCyql() string {
	if x != nil {
		return x.Cyql
	}
	return ""
}

func (x *QueryRequest) GetTenant() string {
	if x != nil {
		return x.Tenant
	}
	return ""
}

func (x *QueryRequest) GetAsOfUnixMs() uint64 {
	if x != nil {
		return x.AsOfUnixMs
	}
	return 0
}

func (x *QueryRequest) GetParams() [][]byte {
	if x != nil {
		return x.Params
	}
	return nil
}

type QueryResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Result rows; each row is an opaque, engine-encoded record.
	Rows          []*QueryRow `protobuf:"bytes,1,rep,name=rows,proto3" json:"rows,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryResponse) Reset() {
	*x = QueryResponse{}
	mi := &file_query_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryResponse) ProtoMessage() {}

func (x *QueryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_query_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryResponse.ProtoReflect.Descriptor instead.
func (*QueryResponse) Descriptor() ([]byte, []int) {
	return file_query_proto_rawDescGZIP(), []int{1}
}

func (x *QueryResponse) GetRows() []*QueryRow {
	if x != nil {
		return x.Rows
	}
	return nil
}

type QueryRow struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Engine-encoded row payload (cybr value bytes). Decoded by the caller.
	Payload       []byte `protobuf:"bytes,1,opt,name=payload,proto3" json:"payload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryRow) Reset() {
	*x = QueryRow{}
	mi := &file_query_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryRow) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryRow) ProtoMessage() {}

func (x *QueryRow) ProtoReflect() protoreflect.Message {
	mi := &file_query_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryRow.ProtoReflect.Descriptor instead.
func (*QueryRow) Descriptor() ([]byte, []int) {
	return file_query_proto_rawDescGZIP(), []int{2}
}

func (x *QueryRow) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

var File_query_proto protoreflect.FileDescriptor

const file_query_proto_rawDesc = "" +
	"\n" +
	"\vquery.proto\x12\x17calystral.core.v1.query\"u\n" +
	"\fQueryRequest\x12\x12\n" +
	"\x04cyql\x18\x01 \x01(\tR\x04cyql\x12\x16\n" +
	"\x06tenant\x18\x02 \x01(\tR\x06tenant\x12!\n" +
	"\ras_of_unix_ms\x18\x03 \x01(\x04R\n" +
	"asOfUnixMs\x12\x16\n" +
	"\x06params\x18\x04 \x03(\fR\x06params\"F\n" +
	"\rQueryResponse\x125\n" +
	"\x04rows\x18\x01 \x03(\v2!.calystral.core.v1.query.QueryRowR\x04rows\"$\n" +
	"\bQueryRow\x12\x18\n" +
	"\apayload\x18\x01 \x01(\fR\apayload2f\n" +
	"\fQueryService\x12V\n" +
	"\x05Query\x12%.calystral.core.v1.query.QueryRequest\x1a&.calystral.core.v1.query.QueryResponseB@Z>github.com/calystral-io/studio/internal/corepb/querypb;querypbb\x06proto3"

var (
	file_query_proto_rawDescOnce sync.Once
	file_query_proto_rawDescData []byte
)

func file_query_proto_rawDescGZIP() []byte {
	file_query_proto_rawDescOnce.Do(func() {
		file_query_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_query_proto_rawDesc), len(file_query_proto_rawDesc)))
	})
	return file_query_proto_rawDescData
}

var file_query_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_query_proto_goTypes = []any{
	(*QueryRequest)(nil),  // 0: calystral.core.v1.query.QueryRequest
	(*QueryResponse)(nil), // 1: calystral.core.v1.query.QueryResponse
	(*QueryRow)(nil),      // 2: calystral.core.v1.query.QueryRow
}
var file_query_proto_depIdxs = []int32{
	2, // 0: calystral.core.v1.query.QueryResponse.rows:type_name -> calystral.core.v1.query.QueryRow
	0, // 1: calystral.core.v1.query.QueryService.Query:input_type -> calystral.core.v1.query.QueryRequest
	1, // 2: calystral.core.v1.query.QueryService.Query:output_type -> calystral.core.v1.query.QueryResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_query_proto_init() }
func file_query_proto_init() {
	if File_query_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_query_proto_rawDesc), len(file_query_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_query_proto_goTypes,
		DependencyIndexes: file_query_proto_depIdxs,
		MessageInfos:      file_query_proto_msgTypes,
	}.Build()
	File_query_proto = out.File
	file_query_proto_goTypes = nil
	file_query_proto_depIdxs = nil
}
