// Vendored from canonical source calystral-io/core/core-api/proto (do not edit by hand; sync via `make proto-sync`).

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v5.29.3
// source: proc.proto

// Stored-procedure registry surface: declare, read, list, and invoke a tenant's
// named CyQL procedures. A proc is a fn-twin (the compiler emits the same
// bytecode as a fn); Core owns the per-tenant catalog of declared procs.
// Declare/read/list round-trip durably and per tenant; invoke dispatch through
// the cvm executor lands with the execution surface (the same opcode gap that
// gaps query execute and mutate), so InvokeProc reports UNIMPLEMENTED today
// rather than faking a result.

package procpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ProcService_DeclareProc_FullMethodName = "/calystral.core.v1.proc.ProcService/DeclareProc"
	ProcService_GetProc_FullMethodName     = "/calystral.core.v1.proc.ProcService/GetProc"
	ProcService_ListProcs_FullMethodName   = "/calystral.core.v1.proc.ProcService/ListProcs"
	ProcService_InvokeProc_FullMethodName  = "/calystral.core.v1.proc.ProcService/InvokeProc"
)

// ProcServiceClient is the client API for ProcService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Manages tenant stored procedures (named CyQL `proc` declarations).
type ProcServiceClient interface {
	// Declare or update a stored procedure for a tenant from its CyQL source.
	DeclareProc(ctx context.Context, in *DeclareProcRequest, opts ...grpc.CallOption) (*DeclareProcResponse, error)
	// Read a tenant's stored procedure definition by name.
	GetProc(ctx context.Context, in *GetProcRequest, opts ...grpc.CallOption) (*GetProcResponse, error)
	// List the names of a tenant's stored procedures.
	ListProcs(ctx context.Context, in *ListProcsRequest, opts ...grpc.CallOption) (*ListProcsResponse, error)
	// Invoke a tenant's stored procedure. Dispatch through the cvm executor lands
	// with the execution surface; today it reports the gap as UNIMPLEMENTED.
	InvokeProc(ctx context.Context, in *InvokeProcRequest, opts ...grpc.CallOption) (*InvokeProcResponse, error)
}

type procServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewProcServiceClient(cc grpc.ClientConnInterface) ProcServiceClient {
	return &procServiceClient{cc}
}

func (c *procServiceClient) DeclareProc(ctx context.Context, in *DeclareProcRequest, opts ...grpc.CallOption) (*DeclareProcResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeclareProcResponse)
	err := c.cc.Invoke(ctx, ProcService_DeclareProc_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *procServiceClient) GetProc(ctx context.Context, in *GetProcRequest, opts ...grpc.CallOption) (*GetProcResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetProcResponse)
	err := c.cc.Invoke(ctx, ProcService_GetProc_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *procServiceClient) ListProcs(ctx context.Context, in *ListProcsRequest, opts ...grpc.CallOption) (*ListProcsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListProcsResponse)
	err := c.cc.Invoke(ctx, ProcService_ListProcs_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *procServiceClient) InvokeProc(ctx context.Context, in *InvokeProcRequest, opts ...grpc.CallOption) (*InvokeProcResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(InvokeProcResponse)
	err := c.cc.Invoke(ctx, ProcService_InvokeProc_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ProcServiceServer is the server API for ProcService service.
// All implementations must embed UnimplementedProcServiceServer
// for forward compatibility.
//
// Manages tenant stored procedures (named CyQL `proc` declarations).
type ProcServiceServer interface {
	// Declare or update a stored procedure for a tenant from its CyQL source.
	DeclareProc(context.Context, *DeclareProcRequest) (*DeclareProcResponse, error)
	// Read a tenant's stored procedure definition by name.
	GetProc(context.Context, *GetProcRequest) (*GetProcResponse, error)
	// List the names of a tenant's stored procedures.
	ListProcs(context.Context, *ListProcsRequest) (*ListProcsResponse, error)
	// Invoke a tenant's stored procedure. Dispatch through the cvm executor lands
	// with the execution surface; today it reports the gap as UNIMPLEMENTED.
	InvokeProc(context.Context, *InvokeProcRequest) (*InvokeProcResponse, error)
	mustEmbedUnimplementedProcServiceServer()
}

// UnimplementedProcServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedProcServiceServer struct{}

func (UnimplementedProcServiceServer) DeclareProc(context.Context, *DeclareProcRequest) (*DeclareProcResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeclareProc not implemented")
}
func (UnimplementedProcServiceServer) GetProc(context.Context, *GetProcRequest) (*GetProcResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetProc not implemented")
}
func (UnimplementedProcServiceServer) ListProcs(context.Context, *ListProcsRequest) (*ListProcsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListProcs not implemented")
}
func (UnimplementedProcServiceServer) InvokeProc(context.Context, *InvokeProcRequest) (*InvokeProcResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method InvokeProc not implemented")
}
func (UnimplementedProcServiceServer) mustEmbedUnimplementedProcServiceServer() {}
func (UnimplementedProcServiceServer) testEmbeddedByValue()                     {}

// UnsafeProcServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ProcServiceServer will
// result in compilation errors.
type UnsafeProcServiceServer interface {
	mustEmbedUnimplementedProcServiceServer()
}

func RegisterProcServiceServer(s grpc.ServiceRegistrar, srv ProcServiceServer) {
	// If the following call panics, it indicates UnimplementedProcServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ProcService_ServiceDesc, srv)
}

func _ProcService_DeclareProc_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeclareProcRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProcServiceServer).DeclareProc(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProcService_DeclareProc_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProcServiceServer).DeclareProc(ctx, req.(*DeclareProcRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProcService_GetProc_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetProcRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProcServiceServer).GetProc(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProcService_GetProc_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProcServiceServer).GetProc(ctx, req.(*GetProcRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProcService_ListProcs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListProcsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProcServiceServer).ListProcs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProcService_ListProcs_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProcServiceServer).ListProcs(ctx, req.(*ListProcsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProcService_InvokeProc_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InvokeProcRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProcServiceServer).InvokeProc(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProcService_InvokeProc_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProcServiceServer).InvokeProc(ctx, req.(*InvokeProcRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ProcService_ServiceDesc is the grpc.ServiceDesc for ProcService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ProcService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "calystral.core.v1.proc.ProcService",
	HandlerType: (*ProcServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "DeclareProc",
			Handler:    _ProcService_DeclareProc_Handler,
		},
		{
			MethodName: "GetProc",
			Handler:    _ProcService_GetProc_Handler,
		},
		{
			MethodName: "ListProcs",
			Handler:    _ProcService_ListProcs_Handler,
		},
		{
			MethodName: "InvokeProc",
			Handler:    _ProcService_InvokeProc_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proc.proto",
}
