// Vendored from canonical source calystral-io/core/core-api/proto (do not edit by hand; sync via `make proto-sync`).

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.29.3
// source: proc.proto

// Stored-procedure registry surface: declare, read, list, and invoke a tenant's
// named CyQL procedures. A proc is a fn-twin (the compiler emits the same
// bytecode as a fn); Core owns the per-tenant catalog of declared procs.
// Declare/read/list round-trip durably and per tenant; invoke dispatch through
// the cvm executor lands with the execution surface (the same opcode gap that
// gaps query execute and mutate), so InvokeProc reports UNIMPLEMENTED today
// rather than faking a result.

package procpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DeclareProcRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Tenant the proc belongs to. Set by the gateway but ignored - the signed
	// principal is the trust boundary.
	Tenant string `protobuf:"bytes,1,opt,name=tenant,proto3" json:"tenant,omitempty"`
	// CyQL source declaring exactly one `proc`.
	Definition    string `protobuf:"bytes,2,opt,name=definition,proto3" json:"definition,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeclareProcRequest) Reset() {
	*x = DeclareProcRequest{}
	mi := &file_proc_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeclareProcRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeclareProcRequest) ProtoMessage() {}

func (x *DeclareProcRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proc_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeclareProcRequest.ProtoReflect.Descriptor instead.
func (*DeclareProcRequest) Descriptor() ([]byte, []int) {
	return file_proc_proto_rawDescGZIP(), []int{0}
}

func (x *DeclareProcRequest) GetTenant() string {
	if x != nil {
		return x.Tenant
	}
	return ""
}

func (x *DeclareProcRequest) GetDefinition() string {
	if x != nil {
		return x.Definition
	}
	return ""
}

type DeclareProcResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The proc name parsed from the definition.
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// The version assigned after applying.
	Version       uint64 `protobuf:"varint,2,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeclareProcResponse) Reset() {
	*x = DeclareProcResponse{}
	mi := &file_proc_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeclareProcResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeclareProcResponse) ProtoMessage() {}

func (x *DeclareProcResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proc_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeclareProcResponse.ProtoReflect.Descriptor instead.
func (*DeclareProcResponse) Descriptor() ([]byte, []int) {
	return file_proc_proto_rawDescGZIP(), []int{1}
}

func (x *DeclareProcResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *DeclareProcResponse) GetVersion() uint64 {
	if x != nil {
		return x.Version
	}
	return 0
}

type GetProcRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Tenant whose proc is requested.
	Tenant string `protobuf:"bytes,1,opt,name=tenant,proto3" json:"tenant,omitempty"`
	// Name of the proc to read.
	Name          string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProcRequest) Reset() {
	*x = GetProcRequest{}
	mi := &file_proc_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProcRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProcRequest) ProtoMessage() {}

func (x *GetProcRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proc_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProcRequest.ProtoReflect.Descriptor instead.
func (*GetProcRequest) Descriptor() ([]byte, []int) {
	return file_proc_proto_rawDescGZIP(), []int{2}
}

func (x *GetProcRequest) GetTenant() string {
	if x != nil {
		return x.Tenant
	}
	return ""
}

func (x *GetProcRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type GetProcResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The current proc version.
	Version uint64 `protobuf:"varint,1,opt,name=version,proto3" json:"version,omitempty"`
	// Proc definition source text.
	Definition    string `protobuf:"bytes,2,opt,name=definition,proto3" json:"definition,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProcResponse) Reset() {
	*x = GetProcResponse{}
	mi := &file_proc_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProcResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProcResponse) ProtoMessage() {}

func (x *GetProcResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proc_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProcResponse.ProtoReflect.Descriptor instead.
func (*GetProcResponse) Descriptor() ([]byte, []int) {
	return file_proc_proto_rawDescGZIP(), []int{3}
}

func (x *GetProcResponse) GetVersion() uint64 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *GetProcResponse) GetDefinition() string {
	if x != nil {
		return x.Definition
	}
	return ""
}

type ListProcsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Tenant whose procs are listed.
	Tenant        string `protobuf:"bytes,1,opt,name=tenant,proto3" json:"tenant,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListProcsRequest) Reset() {
	*x = ListProcsRequest{}
	mi := &file_proc_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListProcsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListProcsRequest) ProtoMessage() {}

func (x *ListProcsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proc_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListProcsRequest.ProtoReflect.Descriptor instead.
func (*ListProcsRequest) Descriptor() ([]byte, []int) {
	return file_proc_proto_rawDescGZIP(), []int{4}
}

func (x *ListProcsRequest) GetTenant() string {
	if x != nil {
		return x.Tenant
	}
	return ""
}

type ListProcsResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The names of the tenant's declared procs, sorted.
	Names         []string `protobuf:"bytes,1,rep,name=names,proto3" json:"names,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListProcsResponse) Reset() {
	*x = ListProcsResponse{}
	mi := &file_proc_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListProcsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListProcsResponse) ProtoMessage() {}

func (x *ListProcsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proc_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListProcsResponse.ProtoReflect.Descriptor instead.
func (*ListProcsResponse) Descriptor() ([]byte, []int) {
	return file_proc_proto_rawDescGZIP(), []int{5}
}

func (x *ListProcsResponse) GetNames() []string {
	if x != nil {
		return x.Names
	}
	return nil
}

type InvokeProcRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Tenant whose proc is invoked.
	Tenant string `protobuf:"bytes,1,opt,name=tenant,proto3" json:"tenant,omitempty"`
	// Name of the proc to invoke.
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	// Encoded argument values, in declaration order. The concrete encoding firms
	// up with the execution surface.
	Args          [][]byte `protobuf:"bytes,3,rep,name=args,proto3" json:"args,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InvokeProcRequest) Reset() {
	*x = InvokeProcRequest{}
	mi := &file_proc_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InvokeProcRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InvokeProcRequest) ProtoMessage() {}

func (x *InvokeProcRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proc_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InvokeProcRequest.ProtoReflect.Descriptor instead.
func (*InvokeProcRequest) Descriptor() ([]byte, []int) {
	return file_proc_proto_rawDescGZIP(), []int{6}
}

func (x *InvokeProcRequest) GetTenant() string {
	if x != nil {
		return x.Tenant
	}
	return ""
}

func (x *InvokeProcRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *InvokeProcRequest) GetArgs() [][]byte {
	if x != nil {
		return x.Args
	}
	return nil
}

type InvokeProcResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Encoded procedure result. Shape firms up with the execution surface.
	Result        []byte `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InvokeProcResponse) Reset() {
	*x = InvokeProcResponse{}
	mi := &file_proc_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InvokeProcResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InvokeProcResponse) ProtoMessage() {}

func (x *InvokeProcResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proc_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InvokeProcResponse.ProtoReflect.Descriptor instead.
func (*InvokeProcResponse) Descriptor() ([]byte, []int) {
	return file_proc_proto_rawDescGZIP(), []int{7}
}

func (x *InvokeProcResponse) GetResult() []byte {
	if x != nil {
		return x.Result
	}
	return nil
}

var File_proc_proto protoreflect.FileDescriptor

const file_proc_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"proc.proto\x12\x16calystral.core.v1.proc\"L\n" +
	"\x12DeclareProcRequest\x12\x16\n" +
	"\x06tenant\x18\x01 \x01(\tR\x06tenant\x12\x1e\n" +
	"\n" +
	"definition\x18\x02 \x01(\tR\n" +
	"definition\"C\n" +
	"\x13DeclareProcResponse\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x18\n" +
	"\aversion\x18\x02 \x01(\x04R\aversion\"<\n" +
	"\x0eGetProcRequest\x12\x16\n" +
	"\x06tenant\x18\x01 \x01(\tR\x06tenant\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\"K\n" +
	"\x0fGetProcResponse\x12\x18\n" +
	"\aversion\x18\x01 \x01(\x04R\aversion\x12\x1e\n" +
	"\n" +
	"definition\x18\x02 \x01(\tR\n" +
	"definition\"*\n" +
	"\x10ListProcsRequest\x12\x16\n" +
	"\x06tenant\x18\x01 \x01(\tR\x06tenant\")\n" +
	"\x11ListProcsResponse\x12\x14\n" +
	"\x05names\x18\x01 \x03(\tR\x05names\"S\n" +
	"\x11InvokeProcRequest\x12\x16\n" +
	"\x06tenant\x18\x01 \x01(\tR\x06tenant\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x12\n" +
	"\x04args\x18\x03 \x03(\fR\x04args\",\n" +
	"\x12InvokeProcResponse\x12\x16\n" +
	"\x06result\x18\x01 \x01(\fR\x06result2\x98\x03\n" +
	"\vProcService\x12f\n" +
	"\vDeclareProc\x12*.calystral.core.v1.proc.DeclareProcRequest\x1a+.calystral.core.v1.proc.DeclareProcResponse\x12Z\n" +
	"\aGetProc\x12&.calystral.core.v1.proc.GetProcRequest\x1a'.calystral.core.v1.proc.GetProcResponse\x12`\n" +
	"\tListProcs\x12(.calystral.core.v1.proc.ListProcsRequest\x1a).calystral.core.v1.proc.ListProcsResponse\x12c\n" +
	"\n" +
	"InvokeProc\x12).calystral.core.v1.proc.InvokeProcRequest\x1a*.calystral.core.v1.proc.InvokeProcResponseB>Z<github.com/calystral-io/studio/internal/corepb/procpb;procpbb\x06proto3"

var (
	file_proc_proto_rawDescOnce sync.Once
	file_proc_proto_rawDescData []byte
)

func file_proc_proto_rawDescGZIP() []byte {
	file_proc_proto_rawDescOnce.Do(func() {
		file_proc_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proc_proto_rawDesc), len(file_proc_proto_rawDesc)))
	})
	return file_proc_proto_rawDescData
}

var file_proc_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_proc_proto_goTypes = []any{
	(*DeclareProcRequest)(nil),  // 0: calystral.core.v1.proc.DeclareProcRequest
	(*DeclareProcResponse)(nil), // 1: calystral.core.v1.proc.DeclareProcResponse
	(*GetProcRequest)(nil),      // 2: calystral.core.v1.proc.GetProcRequest
	(*GetProcResponse)(nil),     // 3: calystral.core.v1.proc.GetProcResponse
	(*ListProcsRequest)(nil),    // 4: calystral.core.v1.proc.ListProcsRequest
	(*ListProcsResponse)(nil),   // 5: calystral.core.v1.proc.ListProcsResponse
	(*InvokeProcRequest)(nil),   // 6: calystral.core.v1.proc.InvokeProcRequest
	(*InvokeProcResponse)(nil),  // 7: calystral.core.v1.proc.InvokeProcResponse
}
var file_proc_proto_depIdxs = []int32{
	0, // 0: calystral.core.v1.proc.ProcService.DeclareProc:input_type -> calystral.core.v1.proc.DeclareProcRequest
	2, // 1: calystral.core.v1.proc.ProcService.GetProc:input_type -> calystral.core.v1.proc.GetProcRequest
	4, // 2: calystral.core.v1.proc.ProcService.ListProcs:input_type -> calystral.core.v1.proc.ListProcsRequest
	6, // 3: calystral.core.v1.proc.ProcService.InvokeProc:input_type -> calystral.core.v1.proc.InvokeProcRequest
	1, // 4: calystral.core.v1.proc.ProcService.DeclareProc:output_type -> calystral.core.v1.proc.DeclareProcResponse
	3, // 5: calystral.core.v1.proc.ProcService.GetProc:output_type -> calystral.core.v1.proc.GetProcResponse
	5, // 6: calystral.core.v1.proc.ProcService.ListProcs:output_type -> calystral.core.v1.proc.ListProcsResponse
	7, // 7: calystral.core.v1.proc.ProcService.InvokeProc:output_type -> calystral.core.v1.proc.InvokeProcResponse
	4, // [4:8] is the sub-list for method output_type
	0, // [0:4] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proc_proto_init() }
func file_proc_proto_init() {
	if File_proc_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proc_proto_rawDesc), len(file_proc_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proc_proto_goTypes,
		DependencyIndexes: file_proc_proto_depIdxs,
		MessageInfos:      file_proc_proto_msgTypes,
	}.Build()
	File_proc_proto = out.File
	file_proc_proto_goTypes = nil
	file_proc_proto_depIdxs = nil
}
